In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[5546, 387, 7443, 1019], [5546, 387, 7443, 128], [5546, 818, 7443, 9325], [7164, 9442, 9911, 1887, 2179], [7164, 9442, 9911, 1887, 6051], [1509, 5546, 1114, 7443, 7129], [7296, 3879, 1280, 1887]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5546  387 7443 1019]
 [   0    0    0    0 5546  387 7443  128]
 [   0    0    0    0 5546  818 7443 9325]
 [   0    0    0 7164 9442 9911 1887 2179]
 [   0    0    0 7164 9442 9911 1887 6051]
 [   0    0    0 1509 5546 1114 7443 7129]
 [   0    0    0    0 7296 3879 1280 1887]]


In [9]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/opt/homebrew/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 248ms/step
[[[-0.04660397 -0.01583793 -0.01681598  0.02681964  0.014161
    0.02494646 -0.04577581 -0.01781303 -0.00365133 -0.02042965]
  [-0.04660397 -0.01583793 -0.01681598  0.02681964  0.014161
    0.02494646 -0.04577581 -0.01781303 -0.00365133 -0.02042965]
  [-0.04660397 -0.01583793 -0.01681598  0.02681964  0.014161
    0.02494646 -0.04577581 -0.01781303 -0.00365133 -0.02042965]
  [-0.04660397 -0.01583793 -0.01681598  0.02681964  0.014161
    0.02494646 -0.04577581 -0.01781303 -0.00365133 -0.02042965]
  [ 0.03859159  0.02149976 -0.0354813   0.02103255  0.02008973
    0.02922944  0.01870651  0.01118958  0.0177439   0.02417243]
  [ 0.0259028  -0.03254992  0.04120232  0.03522544 -0.02407134
    0.02519869 -0.03238164 -0.0424209   0.00231146  0.00047948]
  [ 0.01757673 -0.03938     0.00538025 -0.03193234 -0.03703903
   -0.04062325 -0.04869452 -0.01992422  0.04215061 -0.0330865 ]
  [ 0.03794426  0.00897421  0.00902987 -0.03159416  0.01094164
    0.03753244  0

In [11]:
embedded_docs[0]

array([   0,    0,    0,    0, 5546,  387, 7443, 1019], dtype=int32)

In [12]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
[[-0.04660397 -0.01583793 -0.01681598  0.02681964  0.014161    0.02494646
  -0.04577581 -0.01781303 -0.00365133 -0.02042965]
 [-0.04660397 -0.01583793 -0.01681598  0.02681964  0.014161    0.02494646
  -0.04577581 -0.01781303 -0.00365133 -0.02042965]
 [-0.04660397 -0.01583793 -0.01681598  0.02681964  0.014161    0.02494646
  -0.04577581 -0.01781303 -0.00365133 -0.02042965]
 [-0.04660397 -0.01583793 -0.01681598  0.02681964  0.014161    0.02494646
  -0.04577581 -0.01781303 -0.00365133 -0.02042965]
 [ 0.03859159  0.02149976 -0.0354813   0.02103255  0.02008973  0.02922944
   0.01870651  0.01118958  0.0177439   0.02417243]
 [ 0.0259028  -0.03254992  0.04120232  0.03522544 -0.02407134  0.02519869
  -0.03238164 -0.0424209   0.00231146  0.00047948]
 [ 0.01757673 -0.03938     0.00538025 -0.03193234 -0.03703903 -0.04062325
  -0.04869452 -0.01992422  0.04215061 -0.0330865 ]
 [ 0.03794426  0.00897421  0.00902987 -0.03159416  0.01094164  0.03753244
   0.01388073